name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you so much for using the product, we appreciate your time and effort for your contribution! Please make sure you have used the Issue template and added screenshots (if applicable), it will make our life a little easier. :) We hope to see you and your contributions again!'
        pr-message: 'Wohooo!!! Welcome to the community! We cannot thank you enough for your time and effort that went into this first PR and upcoming PRs of yours, please just make sure you have followed the PR Template and CODE OF CONDUCT. We hope to see you more! :)'
